### ISSUE TITLE
Compiler Error on RPi3 for Kodi 17.1

### ISSUE THREAD

**Issue by MkMunich** [AlwinEsch/pvr.rtl.radiofm#2]
Hi,
I get a compiler error:
pi@raspberrypi:~/pvr.rtl.radiofm/build $ make
[ 20%] Built target rtlsdr_static
[ 20%] Building CXX object CMakeFiles/pvr.rtl.radiofm.dir/src/RadioReceiver.cpp.o
/home/pi/pvr.rtl.radiofm/src/RadioReceiver.cpp: In member function ‘bool cRadioReceiver::OpenChannel(const PVR_CHANNEL&)’:
/home/pi/pvr.rtl.radiofm/src/RadioReceiver.cpp:283:25: error: ‘struct PVR_STREAM_PROPERTIES::PVR_STREAM’ has no member named ‘iPID’
     m_streams.stream[0].iPID            = 1;
                         ^
/home/pi/pvr.rtl.radiofm/src/RadioReceiver.cpp:306:25: error: ‘struct PVR_STREAM_PROPERTIES::PVR_STREAM’ has no member named ‘iPID’
     m_streams.stream[1].iPID            = 2;
                         ^
CMakeFiles/pvr.rtl.radiofm.dir/build.make:86: recipe for target 'CMakeFiles/pvr.rtl.radiofm.dir/src/RadioReceiver.cpp.o' failed
make[2]: *** [CMakeFiles/pvr.rtl.radiofm.dir/src/RadioReceiver.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pvr.rtl.radiofm.dir/all' failed
make[1]: *** [CMakeFiles/pvr.rtl.radiofm.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Before 'make' I executed the following command in subdirectory 'build':
    cmake -DCMAKE_INSTALL_PREFIX=/usr ..

There seems to be 2* xbmc_pvr_types.h on my RPi 3:
pi@raspberrypi:~/pvr.rtl.radiofm/build $ sudo find / -name xbmc_pvr_types.h -print
/usr/include/kodi/xbmc_pvr_types.h
/usr/local/include/kodi/xbmc_pvr_types.h
pi@raspberrypi:~/pvr.rtl.radiofm/build $ grep iPID /usr/include/kodi/xbmc_pvr_types.h /usr/local/include/kodi/xbmc_pvr_types.h
/usr/include/kodi/xbmc_pvr_types.h:      unsigned int      iPID;               /*!< @brief (required) PID */

Means, that only /usr/include/kodi/xbmc_pvr_types.h has member iPID. Why isn't this header taken for the compilation?

**Comment by AlwinEsch** [comment]
Was on a Kodi Version change.

Have updated the addon. For Krypton is there now a branch: https://github.com/AlwinEsch/pvr.rtl.radiofm/tree/Krypton

Sorry it took so long to fix it.
